CREATE TABLE usuarios (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100) NOT NULL,
  email VARCHAR2(255) UNIQUE,
  senha VARCHAR2(100) NOT NULL,
  data_nascimento DATE NOT NULL,
  saldo NUMBER(12, 2)
);
CREATE TABLE eventos (
  id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_criador NUMBER,
  titulo VARCHAR2(255) NOT NULL,
  descricao VARCHAR2(500) NOT NULL,
  valor_cota NUMBER(12, 2),
  data_hora_inicio TIMESTAMP,
  data_hora_fim TIMESTAMP,
  data_evento DATE,
  status VARCHAR2(20) CHECK (status IN ('aprovado', 'reprovado', 'excluido', 'pendente', 'finalizado')),
  resultado VARCHAR2(10) CHECK (resultado IN ('sim', 'nao', 'pendente')),
  CONSTRAINT fk_criador FOREIGN KEY (id_criador) REFERENCES usuarios(id_usuario)
);
CREATE TABLE apostas (
  id_aposta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evento NUMBER,
  id_apostador NUMBER,
  valor_apostado NUMBER(12, 2),
  aposta VARCHAR2(10) CHECK (aposta IN ('sim', 'nao')),
  CONSTRAINT fk_evento FOREIGN KEY (id_evento) REFERENCES eventos(id_evento),
  CONSTRAINT fk_apostador FOREIGN KEY (id_apostador) REFERENCES usuarios(id_usuario)
);
CREATE TABLE transacoes_financeiras (
  id_transacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER,
  tipo_transacao VARCHAR2(20) CHECK (tipo_transacao IN ('credito', 'saque')),
  valor NUMBER(12, 2),
  CONSTRAINT fk_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);